config/routes.rb
Whiteboard::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:edit, :show, :update]

  resources :courses do
    collection do
      post :join
    end
    resources :documents, :announcements, :links
    resources :assignments do
      resources :submissions
      collection do
        put :adjust_weighting
      end
    end
    resources :students do
      collection do
        post :enroll
      end
      member do
        delete :unenroll
      end
    end
    resources :grades
    resources :posts
  end

  resources :professors

  match "feedback" => 'feedback#new', :as => "feedback_form"
  match "feedback/deliver" => 'feedback#deliver', :as => "deliver_feedback"

  root :to => "courses#index"

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :course
  validates_presence_of :subject, :body, :course_id
  
  after_create :send_email
  
  private
  
    def send_email
      course.students.each do |student|
        Notifier.announcement(self, student).deliver
      end
    end
  
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  
  before_filter :set_current_course
  before_filter :ensure_professor_or_admin, :except => :show
  before_filter :ensure_enrolled
  
  def index
    @announcements = @current_course.announcements
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Course.find(params[:course_id]).announcements.build(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(@announcement.course, :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
    def set_current_course
      @current_course ||= Course.find(params[:course_id])
    end
  
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement, :url => course_announcements_path(Course.find(params[:course_id]))) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prevented this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors[:base].each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ol> 
    <li class="string required <%= "error" if @announcement.errors[:subject].any? %>"> 
      <label for="announcement_title">Subject<abbr title="required">*</abbr></label> 
      <%= f.text_field :subject %>
      <% @announcement.errors[:subject].each do |error| %>
         <p class="inline-errors"><%= error %></p> 
      <% end %>
    </li> 
    
    <li class="string required <%= "error" if @announcement.errors[:body].any? %>"> 
      <label for="announcement_body">Body<abbr title="required">*</abbr></label> 
      <%= f.text_area :body %>
      <% @announcement.errors[:body].each do |error| %>
         <p class="inline-errors"><%= error %></p> 
      <% end %>
    </li>
  </ol>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<%= render :partial => "courses/header" %>
<h3>Announcements</h3>

<table>
  <tr>
    <th>Subject</th>
    <th>Date</th>
    <% if %(Admin Professor).include?(current_user.type) %>
    <th>Manage</th>
    <% end %>
  </tr>

<% @announcements.order("created_at DESC").each do |announcement| %>
  <tr>
    <td><%= link_to announcement.subject, course_announcement_path(@current_course, announcement) %></td>
    <td>Posted <%= announcement.created_at.strftime("%m/%d/%Y") %></td>
    <% if %(Admin Professor).include?(current_user.type) %>
    <td>
      <%= link_to edit_course_announcement_path(@current_course, announcement), :class => "grey-button pcb" do %>
        <span>Edit</span>
      <% end %>
      <%= link_to course_announcement_path(@current_course, announcement), :method => :delete, :confirm => "Are you sure you want to delete this announcement?  This cannot be undone!", :class => "red-button pcb" do %>
        <span>Delete</span>
      <% end %>
    </td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/announcements/new.html.erb
<%= render :partial => "courses/header" %>
<h3>New announcement</h3>
<p><b>Please note!</b> Posting this announcement will email all students currently enrolled in your class!  Proofread or they'll never respect you again!</p>
<%= render 'form' %>

app/views/announcements/show.html.erb
<%= render :partial => "courses/header" %>
<h3><%= @announcement.subject %></h3>
<%= simple_format(@announcement.body) %>
<%= link_to "All announcements", course_announcements_path(@current_course) %>