config/routes.rb
Whiteboard::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:edit, :show, :update]

  resources :courses do
    collection do
      post :join
    end
    resources :documents, :announcements, :links
    resources :assignments do
      resources :submissions
      collection do
        put :adjust_weighting
      end
    end
    resources :students do
      collection do
        post :enroll
      end
      member do
        delete :unenroll
      end
    end
    resources :grades
    resources :posts
  end

  resources :professors

  match "feedback" => 'feedback#new', :as => "feedback_form"
  match "feedback/deliver" => 'feedback#deliver', :as => "deliver_feedback"

  root :to => "courses#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :time_zone
  
  has_many :posts
  
  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
  validates_uniqueness_of :email
  
  before_create :set_default_name
  
  def number_of_unread_posts_in(course)
    Post.count_by_sql("SELECT COUNT(*) FROM posts 
      WHERE (posts.course_id = #{course.id} OR posts.id IN (SELECT posts.id from posts INNER JOIN posts parents ON posts.post_id = parents.id AND parents.course_id = #{course.id}))
        AND posts.id NOT IN (SELECT posts.id FROM posts INNER JOIN views ON views.post_id = posts.id and views.user_id = #{self.id}) AND posts.user_id != #{self.id}")
  end
  
  private
  
    def set_default_name
      self.name ||= email.gsub(/@.*/, "")
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :ensure_owner
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user), :notice => "Updated your account information."
    else
      render :action => :edit
    end
  end
  
  private
  
  def ensure_owner
    unless current_user.id.to_s == params[:id]
      redirect_to root_path, :warning => "You don't have permission."
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for(@user, :as => :user, :url => user_path(@user)) do |f| %>
  <% if @user.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% @user.errors[:base].each do |error| %>
          <%= error %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <ol>
    <li class="string <%= "error" if @user.errors[:name].any? %>"> 
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
      <% @user.errors[:name].each do |error| %>
         <p class="inline-errors"><%= error %></p> 
      <% end %>
    </li>
    <li class="string required <%= "error" if @user.errors[:email].any? %>"> 
      <%= f.label :email, raw("Email<abbr>*</abbr>") %>
      <%= f.text_field :email %>
      <% @user.errors[:email].each do |error| %>
         <p class="inline-errors"><%= error %></p> 
      <% end %>
    </li>
    <li class="select">
      <%= f.label :time_zone, "Time Zone" %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :include_blank => true %>
    </li>
    <li class="string required <%= "error" if @user.errors[:password].any? %>"> 
      <%= f.label :password, raw("Password<abbr>*</abbr>") %>
      <%= f.password_field :password %>
      <% @user.errors[:password].each do |error| %>
         <p class="inline-errors"><%= error %></p> 
      <% end %>
    </li>
  </ol>
  <div class="actions">
    <%= submit_tag "Save changes" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Your account</h1>
  
<dl>
  <dt>Name</dt>
  <dd><%= @user.name %></dd>
  <dt>Email</dt>
  <dd><%= @user.email %></dd>
</dl>

<div>
<%= link_to edit_user_path(@user), :class => "grey-button pcb" do %>
  <span>Edit account details</span>
<% end %>
</div>