config/routes.rb
Whiteboard::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:edit, :show, :update]

  resources :courses do
    collection do
      post :join
    end
    resources :documents, :announcements, :links
    resources :assignments do
      resources :submissions
      collection do
        put :adjust_weighting
      end
    end
    resources :students do
      collection do
        post :enroll
      end
      member do
        delete :unenroll
      end
    end
    resources :grades
    resources :posts
  end

  resources :professors

  match "feedback" => 'feedback#new', :as => "feedback_form"
  match "feedback/deliver" => 'feedback#deliver', :as => "deliver_feedback"

  root :to => "courses#index"

end

app/models/professor.rb
class Professor < User
  
  has_many :courses, :foreign_key => "user_id"
  
  def teaching?(course)
    course.professor == self
  end
  
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  
  before_filter :ensure_admin, :except => :show
  
  # GET /professors
  # GET /professors.xml
  def index
    @professors = Professor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @professors }
    end
  end
  
  def show
    @professor = Professor.find(params[:id])
  end

  # GET /professors/new
  # GET /professors/new.xml
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @professor }
    end
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors
  # POST /professors.xml
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to(@professor, :notice => 'Professor was successfully created.') }
        format.xml  { render :xml => @professor, :status => :created, :location => @professor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @professor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /professors/1
  # PUT /professors/1.xml
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to(@professor, :notice => 'Professor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @professor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.xml
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to(professors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ol>
    <li>
      <label>Name</label>
      <%= f.text_field :name %>
    </li>
    <li>
      <label>Email</label>
      <%= f.text_field :email %>
    </li>
    <li>
      <label>Password</label>
      <%= f.password_field :password %>
    </li>
  </ol>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

app/views/professors/index.html.erb
<h1>Listing professors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Manage</th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td>
      <%= link_to professor.name, professor %>
    </td>
    <td>
      <%= link_to 'Edit', edit_professor_path(professor) %>
      <%= link_to 'Destroy', professor, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

app/views/professors/show.html.erb
<h1><%= @professor.name %></h1>
  
<dl>
  <dt>Email</dt>
  <dd><%= mail_to @professor.email %></dd>
  <dt>Teaching</dt>
  <dd><%= @professor.courses.select(&:active?).map(&:title).to_sentence %></dd>
</dl>