config/routes.rb
Whiteboard::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:edit, :show, :update]

  resources :courses do
    collection do
      post :join
    end
    resources :documents, :announcements, :links
    resources :assignments do
      resources :submissions
      collection do
        put :adjust_weighting
      end
    end
    resources :students do
      collection do
        post :enroll
      end
      member do
        delete :unenroll
      end
    end
    resources :grades
    resources :posts
  end

  resources :professors

  match "feedback" => 'feedback#new', :as => "feedback_form"
  match "feedback/deliver" => 'feedback#deliver', :as => "deliver_feedback"

  root :to => "courses#index"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_filter :set_current_course, :except => [:new, :create, :index, :join]
  before_filter :ensure_professor_or_admin, :except => [:show, :index, :join]
  before_filter :ensure_enrolled, :except => [:new, :create, :index, :join]

  skip_before_filter :authenticate_user!, :only => :join

  def index
    @courses = current_user.courses.order("begins_on DESC")
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(params[:course].merge(:user_id => current_user.id))
    if @course.save
      redirect_to(@course, :notice => 'Course was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:course])
      redirect_to(@course, :notice => 'Course was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  def join
    @course = Course.find_by_code(params[:code])
    @student = Student.find_by_email(params[:student][:email]) ||
      Student.new(params[:student].merge(:password => Devise.friendly_token, time_zone: @course.try(:time_zone)))
    respond_to do |format|
      format.json do
        if @course.nil?
          render json: {:error => "Invalid code"}, status: 406
        elsif !@student.save
          render json: {:error => "Invalid email"}, status: 406
        else
          @course.students << @student unless @course.students.include?(@student)
          sign_in(:user, @student)
          render json: {:location => course_url(@course)}, status: 200
        end
      end
    end
  end

  private

    def set_current_course
      @current_course ||= Course.find(params[:id])
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div class="error">
      <h3><%= pluralize(@course.errors.count, "error") %> prevented this course from being saved:</h3>
      <% @course.errors[:base].each do |error| %>
        <%= error %>
      <% end %>
    </div>
  <% end %>

  <ol>
    <li class="string required <%= "error" if @course.errors[:title].any? %>" id="course_title">
      <label for="course_title">Title<abbr title="required">*</abbr></label>
      <%= f.text_field :title %>
      <p class="inline-hints">the name of the course you are teaching</p>
      <% @course.errors[:title].each do |error| %>
         <p class="inline-errors"><%= error %></p>
      <% end %>
    </li>

    <li class="date required" id="course_begins_on">
      <h5 class="legend"><span class="label">Start date<abbr title="required">*</abbr></span></h5>
      <%= f.date_select :begins_on %>
      <% @course.errors[:begins_on].each do |error| %>
         <p class="inline-errors"><%= error %></p>
      <% end %>
    </li>

    <li class="date required" id="course_ends_on">
      <h5 class="legend"><span class="label">End date<abbr title="required">*</abbr></span></h5>
      <%= f.date_select :ends_on %>
      <% @course.errors[:ends_on].each do |error| %>
         <p class="inline-errors"><%= error %></p>
      <% end %>
    </li>

    <li class="select required">
      <h5 class="legend"><span class="label">Time zone<abbr title="required">*</abbr></span></h5>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :include_blank => true %>
      <p class="inline-errors"><%= @course.errors[:time_zone].to_sentence %></p>
    </li>

    <li class="select">
      <h5 class="legend"><span class="label">Code<abbr title="required">*</abbr></span></h5>
      <%= f.text_field :code %>
      <p class="inline-hints">a unique code students can use to register</p>
      <p class="inline-errors"><%= @course.errors[:code].to_sentence %></p>
    </li>
  </ol>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_header.html.erb
<style>
/* make sure the element has position: relative */
[data-notifications] {
  position: relative;
}

/* append the notification badge after it */
[data-notifications]:after {

  /* the burger */
  content: attr(data-notifications);

  /* the fries */
  position: absolute;
  background: red;
  border-radius: 50%;
  display: inline-block;
  padding: 3px;
  color: #f2f2f2;
  right: -10px;
  top: -10px;
  font-weight:bold;
  color:#fff;
  min-width:10px;
  text-align:center;
  font-size:10px;
}
</style>

<% @course ||= Course.find(params[:course_id])%>
<h1 style="display:inline"><%= @course.title %></h1>

<div class="course-nav">
  <%= link_to "Course home", course_path(@course) %>
  <%= link_to "Professor", professor_path(@course.professor) %>
  <%= link_to "Students", course_students_path(@course) %>
  <%= link_to "Grades", course_grades_path(@course) %>
  <%= link_to "Discussion", course_posts_path(@course), "data-notifications" => (current_user.number_of_unread_posts_in(@course) > 0 ? current_user.number_of_unread_posts_in(@course) : nil) %>
</div>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<style>
  tr.inactive {
    display:none;
    background-image:url(/images/diagonal.png);
  }
  
  table#course-listing a {
    color:#000;
  }
  
  table#course-listing tr#toggler td {
    border-bottom:none;
    padding:10px;
  }
  
  a.course-link {
    padding-left:10px;
    font-weight:bold; 
  }
</style>
<h1>Your courses</h1>

<table id="course-listing">
  <tr>
    <th>Title</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Students</th>
    <% if %(Admin Professor).include?(current_user.type) %>
      <th>Manage</th>
    <% end %>
  </tr>

<% (@courses.select(&:active?)+@courses.reject(&:active?)).each do |course| %>
  <tr class="<%= !course.active? ? 'inactive' : nil %>">
    <td><%= link_to course.title, course, :class => "course-link" %></td>
    <td><%= course.begins_on %></td>
    <td><%= course.ends_on %></td>
    <td><%= link_to course.students.count, course_students_path(course) %>
    <% if %(Admin Professor).include?(current_user.type) %>
      <td>
        <%= link_to edit_course_path(course), :class => "grey-button pcb" do %>
          <span>Edit</span>
        <% end %>
        <%= link_to course_path(course), :method => :delete, :confirm => "Are you sure you want to delete this course?  This cannot be undone!", :class => "red-button pcb" do %>
          <span>Delete</span>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
  <tr id="toggler"><td colspan="5" align="center"><%= link_to_function raw("Show all courses &#9660;"), "$('tr.inactive').toggle(); $(this).html(($(this).text() == 'Show all courses ▼') ? 'Show active courses &#9650;' : 'Show all courses &#9660;');" %></td></tr>
</table>



<br />

<% if %(Admin Professor).include?(current_user.type) %>
  <%= link_to new_course_path, :class => "green-button pcb" do %>
    <span>New Course</span>
  <% end %>
<% end %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<style>
  .filelist {
    padding: 20px 0 0 10px;
  }
  
  .filelist dd.top {
    padding: 10px 0 0 10px;
  }
  .filelist dd.bottom {
    padding: 0 0 5px 10px;
  }
  .filelist dt {
  	clear: left;
  	float: left;
  	margin-right: 5px;
  	width: 45px;
  	height: 45px;
  }
  
  .due-date {
    color:red;
    float:right;
  }
</style>

<%= render :partial => "courses/header" %>

<div style="margin-top:20px">
  <h3>Recent announcements</h3>
  <% if @course.announcements.any? %>
    <dl style="padding:15px">
      <% @course.announcements.order("created_at desc").limit(3).each do |announcement| %>
        <dt><%= announcement.subject %></dt>
        <dd><%= truncate_html(announcement.body, :length => 200, :omission => "... "+link_to("(More)", course_announcement_path(@course, announcement))) %>
      <% end %>
    </dl>
  <% else %>
    <div style="margin:20px 50px">No announcements have been posted yet.</div>
  <% end %>
  <div>
  <% if %(Admin Professor).include?(current_user.type) %>
      <%= link_to new_course_announcement_path(@course), :class => "green-button pcb" do %>
        <span>Make an announcement</span>
      <% end %>
  <% end %>
  <%= link_to course_announcements_path(@course), :class => "grey-button pcb" do %>
    <span>All announcements</span>
  <% end %>
  </div>
</div>

<div style="margin-top:20px">
  <h3>Active assignments</h3>
  <% if @course.assignments.written.active.any? %>
  <dl style="padding:15px;position:relative" id="course-assignment-list">
    <% @course.assignments.written.active.order("due_at").each do |assignment| %>
      <dt>
        <%= link_to assignment.name, course_assignment_path(@course, assignment) %>
      </dt>
      <% if current_user.is_a?(Student) %>
        <% unless submission = current_user.submissions.where(:assignment_id => assignment.id).last %>
          <dd class="due-date">DUE: <%= assignment.due_at.to_s(:short) %></dd>
        <% else %>
          <dd class="due-date">Submitted!<dd>
        <% end %>
      <% end %>
      <dd><%= truncate_html(assignment.description, :length => 200, :omission => "... "+link_to("(More)", course_assignment_path(@course, assignment))) %>
    <% end %>
  </dl>
  <% else %>
    <div style="margin:20px 50px">No active assignments.</div>
  <% end %>
  <% if %(Admin Professor).include?(current_user.type) %>
    <div>
      <%= link_to new_course_assignment_path(@course), :class => "green-button pcb" do %>
        <span>Post an assignment</span>
      <% end %>
      <%= link_to course_assignments_path(@course), :class => "grey-button pcb" do %>
        <span>All assignments</span>
      <% end %>
    </div>
  <% end %>
</div>
<div style="margin-top:20px">
  <h3>Course files</h3>
  <% if @course.documents.any? %>
    <dl class="filelist" id="course-file-list">
    <% @course.documents.order("created_at desc").each do |document| %>
      <dt style="position:relative">
        <%= link_to image_tag("doc.png", :width => "100%"), document.attached.url, :class => "file-link" %>
      </dt>
      <dd class="top">
        <h4 style="display:inline"><%= document.name %></h4>
      </dd>
      <dd class="bottom">
        <span style="color:#D8D8D8;"><%= document.description %></span>
      </dd>
    <% end %>
    </dl>
    <div style="clear:both">&nbsp;</div>
  <% else %>
    <div style="margin:20px 50px">No files have been posted yet.</div>
  <% end %>
  <% if %(Admin Professor).include?(current_user.type) %>
    <div>
      <%= link_to new_course_document_path(@course), :class => "green-button pcb" do %>
        <span>Upload a file</span>
      <% end %>
    </div>
  <% end %>
</div>
<div style="margin-top:20px">
  <h3>Course links</h3>
  <% if @course.links.any? %>
    <dl style="padding:15px">
      <% @course.links.order("created_at desc").each do |link| %>
        <dt><%= link_to link.name, link.url %></dt>
        <dd><%= link.description %></dd>
      <% end %>
    </dl>
  <% else %>
    <div style="margin:20px 50px">No links have been posted yet.</div>
  <% end %>
  <% if %(Admin Professor).include?(current_user.type) %>
    <div>
      <%= link_to new_course_link_path(@course), :class => "green-button pcb" do %>
        <span>Post a link</span>
      <% end %>
      <%= link_to course_links_path(@course), :class => "grey-button pcb" do %>
        <span>All links</span>
      <% end %>
    </div>
  <% end %>
</div>